name: Autograding Tests
"on":
  - push
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "release"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas rpy2 pytest pytest-json-report python-dev-tools

      - name: Run Tests
        id: run-all-tests
        run: |
          pytest test_r_functions.py -v --json-report --json-report-file=results.json
          echo "::set-output name=result::$(cat results.json)"

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        if: always()
        with:
          runners: "run-all-tests"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
